### ISSUE TITLE
automatically select the game code text box when opening the 'join game' modal

### ISSUE THREAD

**Issue by Mippy** [ZEIW/ZEIW#35]
so its easier for people who only use keyboards etc. also its just more convenient anyway

**Comment by pnfcre** [comment]
I think this can be achieved without any JS. For example, you can force selection with this CSS:
```css
.force-select-all {
  -webkit-user-select: all;
  user-select: all;
}
```
